/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:f4ee6d00-5cb4-4848-bfe0-489b1b6a3d3b",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_qDaTOP1LW",
    "aws_user_pools_web_client_id": "1e1gm81j1pe7msnfgekh1hn09a",
    "oauth": {}
};


export default awsmobile;
